package com.example.humaraGaon;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.view.ContextMenu;
import android.view.MenuItem;
import android.view.View;
import android.view.animation.Animation;
import android.view.animation.AnimationUtils;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.ListView;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

public class GramBharWarshik extends AppCompatActivity {
    TextView textView;
    ImageView imageView;
    private Spinner spinner1,spinner2,spinner3;
    private Button btnsubmit;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_gram_bhar_warshik);

        imageView=findViewById(R.id.iv_tool);
        textView=findViewById(R.id.tv_tool);


        addItemOnSpinner2();
        addListenerOnButton();
        addListenerOnSpinnerItemSelection();

        addItemOnSpinner3();

        addListenerOnSpinnerItemSelection();



        textView.setText("GramBharatWarshik");

        imageView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startActivity(new Intent(GramBharWarshik.this,Home.class));

            }
        });

    }


    public void addItemOnSpinner3()
    {
        spinner3=(Spinner) findViewById(R.id.spnrblock);
        List<String> list=new ArrayList<>();

        list.add("-Select Block-");
        list.add("Araria");
        list.add("Jokihat");
        list.add("Kursakanta");
        list.add("Raniganj");
        list.add("Sikti");
        list.add("Palasi");
        list.add("Forbesganj");
        list.add("Narpatganj");
        list.add("Bhargama");
        list.add("Bhargama");
        list.add("Arwal");
        list.add("Kaler");
        list.add("Karpi");
        list.add("Kurtha");
        list.add("Sonbhadra Banshi Suryapur");
        list.add("Aurangabad");
        list.add("Barun");
        list.add("Navinagar");
        list.add("Kutumba");
        list.add("Madanpur");
        list.add("Deo");
        list.add("Rafiganj");
        list.add("Obra");
        list.add("Daudnagar");
        list.add("Goh");
        list.add("Haspura");
        list.add("Amarpur");
        list.add("Banka");
        list.add("Barahat");
        list.add("Belhar");
        list.add("Bounsi");
        list.add("Chandan");
        list.add("Dhoraiya");
        list.add("Fullidumer");
        list.add("Katoriya");
        list.add("Rajoun");
        list.add("Sambhuganj");
        list.add("Begusarai");
        list.add("Barauni");
        list.add("Matihani");
        list.add("Birpur");
        list.add("Samho Akha Kurha");
        list.add("Balia");
        list.add("Dandari");
        list.add("Sahebpur Kamal");
        list.add("Teghra");
        list.add("Bachhwara");
        list.add("Bhagwanpur");
        list.add("Mansoorchak");
        list.add("Cheriya Bariyarpur");
        list.add("Chhorahi");
        list.add("Khudabandpur");
        list.add("Bakhari");
        list.add("Garhpura");
        list.add("Nawkothi");
        list.add("Goradih");
        list.add("Jagdishpur");
        list.add("Nathnagar");
        list.add("Sabour");
        list.add("Shahkund");
        list.add("Sultanganj");
        list.add("Kahalgaon");
        list.add("Pirpainty");
        list.add("Sanhaula");
        list.add("Bihpur");
        list.add("Gopalpur");
        list.add("Ismailpur");
        list.add("Kharik");
        list.add("Narayanpur");
        list.add("Rangrachowk");
        list.add("Arrah");
        list.add("Agiaon");
        list.add("Barhara");
        list.add("Koilwar");
        list.add("Udwantnagar");
        list.add("Sandesh");
        list.add("Sahar");
        list.add("Garhani");
        list.add("Piro");
        list.add("Tarari");
        list.add("Jagdishpur");
        list.add("Bihiya");
        list.add("Shahpur");
        list.add("Buxar");
        list.add("Itarhi");
        list.add("Chausa");
        list.add("Rajpur");
        list.add("Dumraon");
        list.add("Nawanagar");
        list.add("Brahampur");
        list.add("Kesath");
        list.add("Chougain");
        list.add("Simri");
        list.add("Darbhanga Sadar");
        list.add("Bahadurpur");
        list.add("Keoti");
        list.add("Singhwara");
        list.add("Jale");
        list.add("Manigachhi");
        list.add("Tardih");
        list.add("Baheri");
        list.add("Hayaghat");
        list.add("Hanuman Nagar");
        list.add("Benipur");
        list.add("Alinagar");
        list.add("Biraul");
        list.add("Ghanshyampur");
        list.add("Kusheshwar Asthan");
        list.add("Kusheshwar Asthan East");
        list.add("Kiratpur");
        list.add("Gaura Bauram");
        list.add("Sangrampur");
        list.add("Harsidhi");
        list.add("Areraj");
        list.add("Paharpur");
        list.add("Chakia");
        list.add("Mehsi");
        list.add("Kesaria");
        list.add("Kalyanpur");
        list.add("Banjaria");
        list.add("Motihari");
        list.add("Piprakothi");
        list.add("Kotowa");
        list.add("Sugauli");
        list.add("Turkaulia");
        list.add("Madhuban");
        list.add("Tetaria");
        list.add("Patahi");
        list.add("Phenhara");
        list.add("Pakaridayal");
        list.add("Raxaul");
        list.add("Ramgarhwa");
        list.add("Adapur");
        list.add("Chauradano");
        list.add("Bankatwa");
        list.add("Chiraiya");
        list.add("Ghorasahan");
        list.add("Dhaka");
        list.add("Gaya Sadar");
        list.add("Belaganj");
        list.add("Wazirganj");
        list.add("Manpur");
        list.add("Bodhgaya");
        list.add("Tankuppa");
        list.add("Fatehpur");
        list.add("Konch");
        list.add("Tekari");
        list.add("Guraru");
        list.add("Paraiya");
        list.add("Khizarsarai");
        list.add("Atri");
        list.add("Bathani");
        list.add("Mohra");
        list.add("Gurua");
        list.add("Amas");
        list.add("Banke Bazar");
        list.add("Imamganj");
        list.add("Dumariya");
        list.add("Sherghati");
        list.add("Dobhi");
        list.add("Mohanpur");
        list.add("Barachatti");
        list.add("Barachatti");
        list.add("Baikunthpur");
        list.add("Barauli");
        list.add("Gopalganj");
        list.add("Kuchaikote");
        list.add("Manjha");
        list.add("Thawe");
        list.add("Sidhwaliya");
        list.add("Bhorey");
        list.add("Hathua");
        list.add("Kateya");
        list.add("Panchdewari");
        list.add("Phulwariya");
        list.add("Uchkagaon");
        list.add("Vijayipur");
        list.add("Jamui");
        list.add("Sikandra");
        list.add("Khaira");
        list.add("Chakai");
        list.add("Sono");
        list.add("Laxmipur");
        list.add("Jhajha");
        list.add("Barhat");
        list.add("Gidhour");
        list.add("IslamnagarAliganj");
        list.add("Jehanabad");
        list.add("Makhdumpur");
        list.add("Ghosi");
        list.add("Hulasganj");
        list.add("Ratni Faridpur");
        list.add("Modanganj");
        list.add("Kako");
        list.add("Adhuara");
        list.add("Bhabhua");
        list.add("Bhagwanpur");
        list.add("Chainpur");
        list.add("Chand");
        list.add("Rampur");
        list.add("Durgawati");
        list.add("Kudra");
        list.add("Mohania");
        list.add("Ramgarh");
        list.add("Nuaon");
        list.add("Katihar");
        list.add("Dandkhora");
        list.add("Hasanganj");
        list.add("Korha");
        list.add("Sameli");
        list.add("Falka");
        list.add("Kursela");
        list.add("Barari");
        list.add("Mansahi");
        list.add("Pranpur");
        list.add("Barsoi");
        list.add("Balrampur");
        list.add("Azamnagar");
        list.add("Kadwa");
        list.add("Manihari");
        list.add("Amdabad");
        list.add("Alauli");
        list.add("Khagaria");
        list.add("Chautham");
        list.add("Mansi");
        list.add("Gogri");
        list.add("Beldaur");
        list.add("Parbatta");
        list.add("Sadar Lakhisarai");
        list.add("Barahiya");
        list.add("Pipariya");
        list.add("Halsi");
        list.add("Chanan");
        list.add("Ramgarh Chowk");
        list.add("Surajgarha");
        list.add("Rahika");
        list.add("Pandaul");
        list.add("Rajnagar");
        list.add("Babubarhi");
        list.add("Kaluahi");
        list.add("Khjauli");
        list.add("Jainagar");
        list.add("Ladaniya");
        list.add("Basopatti");
        list.add("Bisfi");
        list.add("Harlakhi");
        list.add("Madhwapur");
        list.add("Jhanjarpur");
        list.add("Andhrathadi");
        list.add("Lakhnaur");
        list.add("Madhepur");
        list.add("Phulparas");
        list.add("Ghoghardiha");
        list.add("Khutauna");
        list.add("Laukahi");
        list.add("Sadar");
        list.add("Jamalpur");
        list.add("Bariyarpur");
        list.add("Dharhara");
        list.add("H. Kharagpur");
        list.add("Tetiyabambar");
        list.add("Tarapur");
        list.add("Sangrampur");
        list.add("Asarganj");
        list.add("AURAI");
        list.add("BANDRA");
        list.add("BOCHAHAN");
        list.add("GAIGHAT");
        list.add("MUSHAHARI");
        list.add("KATRA");
        list.add("MINAPUR");
        list.add("MURAUL");
        list.add("SAKRA");
        list.add("KANTI");
        list.add("KURHANI");
        list.add("MARWAN");
        list.add("PAROO");
        list.add("SAHEBGANJ");
        list.add("MOTIPUR");
        list.add("SARAIYA");
        list.add("Giriyak");
        list.add("Rahui");
        list.add("Ajaypur Noorsarai");
        list.add("Harnaut");
        list.add("Chandi (Nalanda)");
        list.add("Islampur (Nalanda)");
        list.add("Rajgir");
        list.add("Asthawan");
        list.add("Sarmera");
        list.add("Hilsa");
        list.add("Biharsharif");
        list.add("Ekangarsarai");
        list.add("Bena");
        list.add("Nagarnausa");
        list.add("Karai Parsarai");
        list.add("Silao");
        list.add("Parwalpur");
        list.add("Katrisarai");
        list.add("Bind");
        list.add("Tharthar");
        list.add("Hisua");
        list.add("Kashichak");
        list.add("Kawakole");
        list.add("Nardiganj");
        list.add("Nawada");
        list.add("Pakribarawan");
        list.add("Warisaliganj");
        list.add("Akbarpur");
        list.add("Govindpur");
        list.add("Meskaur");
        list.add("Narhat");
        list.add("NRajauli");
        list.add("Roh");
        list.add("Siradala");
        list.add("Patna Sadar");
        list.add("Sampatchak");
        list.add("Phulwarisarif");
        list.add("Fatwah");
        list.add("Daniyawan");
        list.add("Khusrupur");
        list.add("Athmal gola");
        list.add("Mokama");
        list.add("Belchhi");
        list.add("Ghoswari");
        list.add("Pandarak");
        list.add("Bakhtiyarpur");
        list.add("Barh");
        list.add("Masaurhi");
        list.add("Punpuni");
        list.add("Dhanarua");
        list.add("Danapur");
        list.add("Maner");
        list.add("Bihta");
        list.add("Naubatpur");
        list.add("Paliganj");
        list.add("Dulhinbazar");
        list.add("Bikram");
        list.add("Purnea east");
        list.add("Jalalgarh");
        list.add("kasba");
        list.add("Krityanand Nagar");
        list.add("Srinagar");
        list.add("Dhamdaha");
        list.add("Rupauli");
        list.add("Bhawanipur");
        list.add("Barhara");
        list.add("Amour");
        list.add("Baisa");
        list.add("Baisi");
        list.add("Dagarua");
        list.add("Banmankhi");
        list.add("Sasaram");
        list.add("Shivsagar");
        list.add("Chenari");
        list.add("Kargahar");
        list.add("Kochas");
        list.add("Nokha");
        list.add("Dehri");
        list.add("Akodhigola");
        list.add("Nauhatta");
        list.add("Rohtas");
        list.add("Tilouthu");
        list.add("Bikramganj");
        list.add("Karakat");
        list.add("Nasriganj");
        list.add("Dawath");
        list.add("Rajpur");
        list.add("Sanjhauli");
        list.add("Suryapura");
        list.add("Dinara");
        list.add("Kahara");
        list.add("Sattar Kataiya");
        list.add("Nauhatta");
        list.add("Mahishi");
        list.add("Sonbarsa");
        list.add("Sour Bazar");
        list.add("Patarghat");
        list.add("Simri Bakhtiyarpur");
        list.add("Salkhua");
        list.add("Banma Itahri");
        list.add("Samastipur");
        list.add("Tajpur");
        list.add("Morwa");
        list.add("Khanpur");
        list.add("Sarairanjan");
        list.add("Pusa");
        list.add("Warishnagar");
        list.add("Kalyanpur");
        list.add("Rosera");
        list.add("Hasanpur");
        list.add("Bithan");
        list.add("Shivajinagar");
        list.add("Singhiya");
        list.add("Bibhutipur");
        list.add("Dalsingsarai");
        list.add("Ujiyarpur");
        list.add("Vidyapatinagar");
        list.add("Patori");
        list.add("Mohanpur");
        list.add("Mohiuddin Nagar");
        list.add("Chapra");
        list.add("Manjhi");
        list.add("Dighwara");
        list.add("Rivilganj");
        list.add("Parsa");
        list.add("Baniapur");
        list.add("Amnaur");
        list.add("Taraiya");
        list.add("Sonpur");
        list.add("Garkha");
        list.add("Ekma");
        list.add("Dariyapur");
        list.add("Jalalpur");
        list.add("Marhaura");
        list.add("Mashrakh");
        list.add("Maker");
        list.add("Nagra");
        list.add("Panapur");
        list.add("Eisuapur");
        list.add("Lahladpur");
        list.add("Sheikhpura");
        list.add("Ghatkusumbha");
        list.add("Chewara");
        list.add("Barbigha");
        list.add("Sheikhopur Sarai");
        list.add("Ariyari");
        list.add("Sheohar");
        list.add("Tariyani");
        list.add("Dumri Katsari");
        list.add("Piprahi");
        list.add("Purnahiya");
        list.add("Bairgania");
        list.add("Bajpatti");
        list.add("Bathnaha");
        list.add("Belsand");
        list.add("Bokhra");
        list.add("Choraut");
        list.add("Dumra");
        list.add("Majorganj");
        list.add("Nanpur");
        list.add("Parihar");
        list.add("Parsauni");
        list.add("Pupri");
        list.add("Riga");
        list.add("Runni Saidpur");
        list.add("Sonbarsa");
        list.add("Suppi");
        list.add("Sursand");
        list.add("Basantpur");
        list.add("Basantpur Hat");
        list.add("Goriakothi");
        list.add("Lakri Nabiganj");
        list.add("Maharaganj");
        list.add("Daraundha");
        list.add("Andar");
        list.add("Barharia");
        list.add("Darauli");
        list.add("Guthani");
        list.add("Hasan Pura");
        list.add("Hussainganj");
        list.add("Mairwa");
        list.add("Nautan");
        list.add("Pachrukhi");
        list.add("Raghunathpur");
        list.add("Siswan");
        list.add("Siwan Sadar");
        list.add("Ziradei");
        list.add("Supaul");
        list.add("Kishanpur");
        list.add("Saraigarh-Bhaptiyahi");
        list.add("Pipra");
        list.add("Triveniganj");
        list.add("Raghopur");
        list.add("Chhatapur");
        list.add("Nirmali");
        list.add("Marauna");
        list.add("Basantpur");
        list.add("Pratapganj");
        list.add("Mahnar");
        list.add("Vaishali");
        list.add("Bidupur");
        list.add("Goraul");
        list.add("Raghopur");
        list.add("Lalganj");
        list.add("Hajipur");
        list.add("Mahua");
        list.add("Jandaha");
        list.add("Patepur");
        list.add("Sahdei Buzurg");
        list.add("Bhagwanpur");
        list.add("Chehrakala");
        list.add("Rajapakar");
        list.add("Patedhi Belsar");
        list.add("Desari");
        list.add("Bettiah");
        list.add("Piprasi");
        list.add("Nautan");
        list.add("Bairiya");
        list.add("Majhaulia");
        list.add("Bhitaha");
        list.add("Lauriya");
        list.add("Chanpatia");
        list.add("Mainatand");
        list.add("Sikta");
        list.add("Yogapatti");
        list.add("Narkatiaganj");
        list.add("Gaunaha");
        list.add("Ramnagar");
        list.add("Bagaha 1");
        list.add("Bagaha 2");
        list.add("Thakaraha");
        list.add("Madhubani");




        ArrayAdapter<String> dataAdapter=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,list);
        dataAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        spinner3.setAdapter(dataAdapter);
    }

    public void addListenerItemSelection2()
    {
        spinner2=(Spinner) findViewById(R.id.spnrsubdvsn);
        spinner2.setOnItemSelectedListener(new AnotherJAva());
    }

    public void addItemOnSpinner2()
    {
        spinner2=(Spinner) findViewById(R.id.spnrsubdvsn);
        List<String> list=new ArrayList<>();
        list.add("Select Division");
        list.add("Araria");
        list.add("Forbesganj");
        list.add("Arwal");
        list.add("Aurangabad");
        list.add("Daudnagar");
        list.add("Banka");
        list.add("Begusarai");
        list.add("Balia");
        list.add("Teghra");
        list.add("Manjhaul");
        list.add("Bakhari");
        list.add("Bhagalpur Sadar");
        list.add("Kahalgaon");
        list.add("Naugachhia");
        list.add("Ara–Sadar");
        list.add("Piro");
        list.add("Jagdishpur");
        list.add("Buxar");
        list.add("Dumraon");
        list.add("Darbhanga Sadar");
        list.add("Benipur");
        list.add("Biraul");
        list.add("Areraj");
        list.add("Chakia");
        list.add("Motihari");
        list.add("Pakaridayal");
        list.add("Sihrahana");
        list.add("Sadar");
        list.add("Tekari");
        list.add("Neemchak Bathani");
        list.add("Sherghati");
        list.add("Gopalganj");
        list.add("Hathua");
        list.add("Jamui");
        list.add("Jehanabad");
        list.add("Bhabhua");
        list.add("Mohania");
        list.add("Katihar");
        list.add("Barsoi");
        list.add("Manihari");
        list.add("Khagaria");
        list.add("Gogri");
        list.add("Kishanganj");
        list.add("Lakhisarai");
        list.add("Madhepura");
        list.add("Madhubani Sadar");
        list.add("Benipatti");
        list.add("Jhanjarpur");
        list.add("Phulparas");
        list.add("Jainagar");
        list.add("Munger Sadar");
        list.add("H. Kharagpur");
        list.add("Tarapur");
        list.add("Subdivision East");
        list.add("Subdivision West");
        list.add("Biharsharif");
        list.add("Hilsa");
        list.add("Rajgir");
        list.add("Nawada");
        list.add("Rajauli");
        list.add("Patna Sadar");
        list.add("Patna City");
        list.add("Barh");
        list.add("Masaurhi");
        list.add("Danapur");
        list.add("Paliganj");
        list.add("Purnea Sadar");
        list.add("Dhamdaha");
        list.add("Baisi");
        list.add("Banmankhi");
        list.add("Sasaram");
        list.add("Dehri");
        list.add("Bikramganj");
        list.add("Saharsa");
        list.add("Simri Bakhtiyarpur");
        list.add("Samastipur");
        list.add("Dalsingsarai");
        list.add("Rosera");
        list.add("Patori");
        list.add("Sadar Chapra");
        list.add("Marhaura");
        list.add("Sonpur");
        list.add("Sheikhpura");
        list.add("Sheohar");
        list.add("Sitamarhi Sadar");
        list.add("Pupri");
        list.add("Belsand");
        list.add("Maharajganj");
        list.add("Sadar Siwan");
        list.add("Supaul Sadar");
        list.add("Triveniganj");
        list.add("Birpur");
        list.add("Nirmali");
        list.add("Hajipur");
        list.add("Mahnar");
        list.add("Mahua");
        list.add("Bettiah");
        list.add("Narkatiaganj");
        list.add("Bagaha");


        ArrayAdapter<String> dataAdapter=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_item,list);
        dataAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        spinner2.setAdapter(dataAdapter);
    }
    public void addListenerOnSpinnerItemSelection()
    {
        spinner1=(Spinner) findViewById(R.id.spnrDistrict);
        spinner1.setOnItemSelectedListener(new AnotherJAva());
    }

    public void addListenerOnButton()
    {
        spinner1=(Spinner) findViewById(R.id.spnrDistrict);
        spinner1=(Spinner) findViewById(R.id.spnrsubdvsn);
        btnsubmit=(Button) findViewById(R.id.go);


        btnsubmit.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                Toast.makeText(GramBharWarshik.this,
                        "OnClickListener : " +
                                "\nSpinner 1 : " + String.valueOf(spinner1.getSelectedItem()) +
                                "\nSpinner 2 : " + String.valueOf(spinner2.getSelectedItem())+
                                "\nSpinner 3:"+String.valueOf(spinner3.getSelectedItem()),
                        Toast.LENGTH_SHORT).show();
                startActivity(new Intent(GramBharWarshik.this,GaonPatna.class));


            }
        });
    }


}
